### PR TITLE
Feature: Include Allow third-party fusion code for fusion forms

### LINKED ISSUE #9: Allow Foreign Fusion Prototypes and Eel Helpers to be used
With `renderingOptions._fusionRuntime` an existing FusionRuntime can be reused to render a form and this is used by the [Neos.Form.Builder](https://github.com/neos/form-builder).
If used "stand alone" there is no FusionRuntime, so it is built in the 
[FusionFormRenderer](https://github.com/neos/form-fusionrenderer/blob/master/Classes/FusionFormRenderer.php#L86-L97) explicitly including required Fusion files.
This list should be extensible (via Settings for example).

Besides, the configured Eel Helpers should be available (if that's not the case already)

### PR DESCRIPTION
**Pull request by daniellienert**
Fusion code from additional packages can be loaded
using a similar configuration to `Neos.Neos.fusion.autoInclude`

Fixes: #9

### CODE REVIEW

**Comment by daniellienert** [comment]
Includes #20

**Comment by bwaidelich** [comment]
Great, thanks for this. Looks great by reading but it would be nice if we could add a short example to the README, don't you think?

**Comment by daniellienert** [comment]
Sure, if we'll do it this way, I add some documentation

**Comment by bwaidelich** [comment]
> Sure, if we'll do it this way, I add some documentation

I think, it makes a lot of sense and is not breaking!

**Review by bwaidelich — APPROVED** [review]
Looks good, by reading. Thanks!

**Pull request merged**
