### PR TITLE
FEATURE: Compatibility with neos/flow v9.0

### PR DESCRIPTION
**Pull request by c4ll-m3-j4ck**
With version 9.0, previously deprecated fusion prototypes have been removed. This PR replaces the removed prototypes with the suggested replacements.

### CODE REVIEW

**Review by kdambekalns — APPROVED** [review]
👍 by 👀

**Comment by dlubitz** [comment]
I moved two changes from the duplicate https://github.com/neos/form-fusionrenderer/pull/30 PR to complete this.

**Review by dlubitz — APPROVED** [review]

**Comment by dlubitz** [comment]
Before we merge this, I wonder if we need to raise the version constraint here for neos/form? Or add a version constraint for Neos 9?

**Review by kdambekalns — APPROVED** [review]

**Comment by dlubitz** [comment]
Actually it should have a dependency to fusion, but yeah, not part of this PR.

**Comment by kdambekalns** [comment]
> Before we merge this, I wonder if we need to raise the version constraint here for neos/form? Or add a version constraint for Neos 9?

The "new" prototypes used are nothing specific to Neos 9, and the (transitive) dependency chain looks good to me…

**Comment by kdambekalns** [comment]
`neos/form-fusionrenderer` needs `neos/form` needs `neos/flow` – but no `neos/fusion`, right. Good catch!

**Comment by dlubitz** [comment]
Thank you @c4ll-m3-j4ck for your contribution. I created a new release with this change
https://github.com/neos/form-fusionrenderer/releases/tag/2.2.0

**Pull request merged**
